// frontend/src/pages/OpenApi/index.tsx
import { useEffect, useState } from 'react'
import {
  Card, Table, Button, Space, Modal, Form, Input,
  Select, Switch, Typography, message, Popconfirm,
  Tag, Tooltip, InputNumber, Alert,
} from 'antd'
import {
  PlusOutlined, ReloadOutlined, DeleteOutlined,
  EditOutlined, CopyOutlined, SyncOutlined, EyeOutlined, EyeInvisibleOutlined,
} from '@ant-design/icons'
import { openApiApi } from '../../services/api'

const { Title, Text, Paragraph } = Typography

const SCOPE_OPTIONS = [
  { label: '任务管理', value: 'tasks' },
  { label: '脚本管理', value: 'scripts' },
  { label: '环境变量', value: 'envs' },
  { label: '日志查看', value: 'logs' },
  { label: '系统信息', value: 'system' },
]

interface AppRecord {
  id: number
  name: string
  client_id: string
  client_secret?: string
  scopes: string[]
  token_expiry: number
  enabled: boolean
  last_used_at: string | null
  created_at: string
}

export default function OpenApi() {
  const [apps, setApps] = useState<AppRecord[]>([])
  const [loading, setLoading] = useState(false)
  const [modalOpen, setModalOpen] = useState(false)
  const [editingApp, setEditingApp] = useState<AppRecord | null>(null)
  const [createdSecret, setCreatedSecret] = useState<{ clientId: string; clientSecret: string } | null>(null)
  const [form] = Form.useForm()
  const [visibleSecrets, setVisibleSecrets] = useState<Record<number, string>>({})
  const [loadingSecrets, setLoadingSecrets] = useState<Record<number, boolean>>({})

  useEffect(() => {
    fetchApps()
  }, [])

  const fetchApps = async () => {
    setLoading(true)
    try {
      const res = await openApiApi.listApps()
      setApps(res.data.data || [])
    } catch {
      message.error('获取应用列表失败')
    } finally {
      setLoading(false)
    }
  }

  const handleCreate = () => {
    setEditingApp(null)
    form.resetFields()
    form.setFieldsValue({ token_expiry: 2592000, scopes: [] })
    setModalOpen(true)
  }

  const handleEdit = (record: AppRecord) => {
    setEditingApp(record)
    form.setFieldsValue(record)
    setModalOpen(true)
  }

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields()
      if (editingApp) {
        await openApiApi.updateApp(editingApp.id, values)
        message.success('更新成功')
        setModalOpen(false)
      } else {
        const res = await openApiApi.createApp(values)
        const data = res.data.data
        setCreatedSecret({
          clientId: data.client_id,
          clientSecret: data.client_secret,
        })
        setModalOpen(false)
      }
      fetchApps()
    } catch (err: any) {
      if (err?.response?.data?.error) {
        message.error(err.response.data.error)
      }
    }
  }

  const handleDelete = async (id: number) => {
    try {
      await openApiApi.deleteApp(id)
      message.success('删除成功')
      fetchApps()
    } catch {
      message.error('删除失败')
    }
  }

  const handleResetSecret = async (id: number) => {
    try {
      const res = await openApiApi.resetSecret(id)
      const app = apps.find((a) => a.id === id)
      setCreatedSecret({
        clientId: app?.client_id || '',
        clientSecret: res.data.client_secret,
      })
      // 清除该应用的可见状态
      setVisibleSecrets(prev => {
        const next = { ...prev }
        delete next[id]
        return next
      })
      message.success('Secret 已重置')
    } catch {
      message.error('重置失败')
    }
  }

  const handleToggle = async (record: AppRecord) => {
    try {
      await openApiApi.updateApp(record.id, { enabled: !record.enabled })
      message.success(record.enabled ? '已禁用' : '已启用')
      fetchApps()
    } catch {
      message.error('操作失败')
    }
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
    message.success('已复制到剪贴板')
  }

  const handleToggleSecret = async (id: number) => {
    if (visibleSecrets[id]) {
      // 隐藏
      setVisibleSecrets(prev => {
        const next = { ...prev }
        delete next[id]
        return next
      })
    } else {
      // 弹窗输入密码进行二次验证
      let passwordValue = ''
      Modal.confirm({
        title: '安全验证',
        content: (
          <div>
            <p style={{ marginBottom: 8, color: '#666' }}>查看 Client Secret 需要验证当前登录密码</p>
            <Input.Password
              placeholder="请输入当前登录密码"
              onChange={e => { passwordValue = e.target.value }}
              onPressEnter={() => {
                // Enter 键触发确认
                const btn = document.querySelector('.ant-modal-confirm-btns .ant-btn-primary') as HTMLElement
                btn?.click()
              }}
            />
          </div>
        ),
        okText: '验证',
        cancelText: '取消',
        onOk: async () => {
          if (!passwordValue) {
            message.warning('请输入密码')
            throw new Error('密码为空')
          }
          setLoadingSecrets(prev => ({ ...prev, [id]: true }))
          try {
            const res = await openApiApi.getSecret(id, passwordValue)
            setVisibleSecrets(prev => ({ ...prev, [id]: res.data.client_secret }))
          } catch (err: any) {
            const errMsg = err?.response?.data?.error || '获取 Secret 失败'
            message.error(errMsg)
            throw err
          } finally {
            setLoadingSecrets(prev => ({ ...prev, [id]: false }))
          }
        },
      })
    }
  }

  const columns = [
    {
      title: '应用名称',
      dataIndex: 'name',
      key: 'name',
      width: 160,
    },
    {
      title: 'Client ID',
      dataIndex: 'client_id',
      key: 'client_id',
      width: 280,
      render: (v: string) => (
        <Space>
          <code style={{ fontSize: 12 }}>{v}</code>
          <Tooltip title="复制">
            <Button type="text" size="small" icon={<CopyOutlined />} onClick={() => copyToClipboard(v)} />
          </Tooltip>
        </Space>
      ),
    },
    {
      title: 'Client Secret',
      key: 'client_secret',
      width: 320,
      render: (_: any, record: AppRecord) => {
        const isVisible = !!visibleSecrets[record.id]
        const isLoading = !!loadingSecrets[record.id]
        return (
          <Space>
            <code style={{ fontSize: 12 }}>
              {isVisible ? visibleSecrets[record.id] : '••••••••••••••••'}
            </code>
            <Tooltip title={isVisible ? '隐藏' : '显示'}>
              <Button
                type="text"
                size="small"
                icon={isVisible ? <EyeInvisibleOutlined /> : <EyeOutlined />}
                loading={isLoading}
                onClick={() => handleToggleSecret(record.id)}
              />
            </Tooltip>
            {isVisible && (
              <Tooltip title="复制">
                <Button
                  type="text"
                  size="small"
                  icon={<CopyOutlined />}
                  onClick={() => copyToClipboard(visibleSecrets[record.id])}
                />
              </Tooltip>
            )}
          </Space>
        )
      },
    },
    {
      title: '权限',
      dataIndex: 'scopes',
      key: 'scopes',
      width: 200,
      render: (scopes: string[]) => (
        <Space wrap size={4}>
          {scopes.length === 0 ? (
            <Tag>全部权限</Tag>
          ) : (
            scopes.map((s) => <Tag key={s} color="blue">{s}</Tag>)
          )}
        </Space>
      ),
    },
    {
      title: '状态',
      dataIndex: 'enabled',
      key: 'enabled',
      width: 80,
      render: (enabled: boolean, record: AppRecord) => (
        <Switch size="small" checked={enabled} onChange={() => handleToggle(record)} />
      ),
    },
    {
      title: '操作',
      key: 'actions',
      width: 180,
      render: (_: any, record: AppRecord) => (
        <Space size={4}>
          <Tooltip title="编辑">
            <Button type="text" size="small" icon={<EditOutlined />} onClick={() => handleEdit(record)} />
          </Tooltip>
          <Popconfirm title="重置 Secret 后旧 Secret 将失效，确定？" onConfirm={() => handleResetSecret(record.id)}>
            <Tooltip title="重置 Secret">
              <Button type="text" size="small" icon={<SyncOutlined />} />
            </Tooltip>
          </Popconfirm>
          <Popconfirm title="确定删除？" onConfirm={() => handleDelete(record.id)}>
            <Tooltip title="删除">
              <Button type="text" size="small" icon={<DeleteOutlined />} danger />
            </Tooltip>
          </Popconfirm>
        </Space>
      ),
    },
  ]

  return (
    <div className="animate-fade-in">
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
        <Title level={4} style={{ margin: 0, fontWeight: 600 }}>开放 API</Title>
        <Space>
          <Button icon={<ReloadOutlined />} onClick={fetchApps}>刷新</Button>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleCreate}>新建应用</Button>
        </Space>
      </div>

      <Card style={{ borderRadius: 10 }} styles={{ body: { padding: 0 } }}>
        <Table
          dataSource={apps}
          columns={columns}
          rowKey="id"
          loading={loading}
          size="middle"
          scroll={{ y: 600 }}
          virtual
          pagination={false}
          locale={{ emptyText: '暂无应用' }}
        />
      </Card>

      {/* 创建/编辑弹窗 */}
      <Modal
        title={editingApp ? '编辑应用' : '新建应用'}
        open={modalOpen}
        onOk={handleSubmit}
        onCancel={() => setModalOpen(false)}
        okText="保存"
        cancelText="取消"
        destroyOnClose
      >
        <Form form={form} layout="vertical" style={{ marginTop: 16 }}>
          <Form.Item
            name="name"
            label="应用名称"
            rules={[{ required: true, message: '请输入应用名称' }]}
          >
            <Input placeholder="例如：外部调度系统" />
          </Form.Item>
          <Form.Item name="scopes" label="权限范围">
            <Select
              mode="multiple"
              placeholder="留空表示全部权限"
              options={SCOPE_OPTIONS}
              allowClear
            />
          </Form.Item>
          <Form.Item
            name="token_expiry"
            label="Access Token 有效期（秒）"
            tooltip="每次获取的 Access Token 的有效期，过期后需重新获取。Client Secret 永久有效。"
          >
            <InputNumber
              min={3600}
              max={31536000}
              style={{ width: '100%' }}
              placeholder="默认 2592000 秒（30天）"
            />
          </Form.Item>
        </Form>
      </Modal>

      {/* Secret 展示弹窗 */}
      <Modal
        title="应用凭证"
        open={!!createdSecret}
        onCancel={() => setCreatedSecret(null)}
        footer={[
          <Button key="ok" type="primary" onClick={() => setCreatedSecret(null)}>
            我已保存
          </Button>,
        ]}
      >
        <Alert
          type="warning"
          message="请妥善保管 Client Secret，关闭后将无法再次查看"
          style={{ marginBottom: 16 }}
        />
        {createdSecret && (
          <div>
            <div style={{ marginBottom: 12 }}>
              <Text type="secondary" style={{ fontSize: 12 }}>Client ID</Text>
              <Paragraph
                copyable
                code
                style={{ fontSize: 13, marginBottom: 0, marginTop: 4 }}
              >
                {createdSecret.clientId}
              </Paragraph>
            </div>
            <div>
              <Text type="secondary" style={{ fontSize: 12 }}>Client Secret</Text>
              <Paragraph
                copyable
                code
                style={{ fontSize: 13, marginBottom: 0, marginTop: 4 }}
              >
                {createdSecret.clientSecret}
              </Paragraph>
            </div>
          </div>
        )}
      </Modal>
    </div>
  )
}

// web/src/views/open-api/index.vue
<template>
  <div>
    <div class="page-header">
      <div>
        <h2>Open API 管理</h2>
        <span class="page-subtitle">创建和管理外部 API 调用应用密钥</span>
      </div>
      <el-button type="primary" @click="showCreateDialog">创建应用</el-button>
    </div>

    <el-table :data="apps" v-loading="loading" border>
      <el-table-column prop="name" label="应用名称" min-width="120" />
      <el-table-column label="App Key" min-width="280">
        <template #default="{ row }">
          <div class="key-display">
            <code class="key-code">{{ row.app_key }}</code>
            <el-button class="copy-btn" size="small" @click="copyText(row.app_key)">
              <el-icon><DocumentCopy /></el-icon>
            </el-button>
          </div>
        </template>
      </el-table-column>
      <el-table-column label="App Secret" min-width="280">
        <template #default="{ row }">
          <div class="key-display">
            <template v-if="revealedSecrets[row.id]">
              <code class="key-code secret-code">{{ revealedSecrets[row.id] }}</code>
              <el-button class="copy-btn" size="small" @click="copyText(revealedSecrets[row.id] || '')">
                <el-icon><DocumentCopy /></el-icon>
              </el-button>
              <el-button class="copy-btn" size="small" @click="delete revealedSecrets[row.id]">
                <el-icon><Hide /></el-icon>
              </el-button>
            </template>
            <template v-else>
              <span class="secret-mask">••••••••••••••••</span>
              <el-button type="primary" link size="small" @click="viewSecret(row)">
                <el-icon><View /></el-icon>查看
              </el-button>
            </template>
          </div>
        </template>
      </el-table-column>
      <el-table-column label="权限范围" min-width="180">
        <template #default="{ row }">
          <el-tag
            v-for="s in parseScopesTags(row.scopes)"
            :key="s"
            size="small"
            style="margin: 2px 4px 2px 0"
          >{{ s }}</el-tag>
          <span v-if="!row.scopes" style="color: var(--el-text-color-secondary)">全部权限</span>
        </template>
      </el-table-column>
      <el-table-column prop="rate_limit" label="速率限制" width="100" align="center" />
      <el-table-column prop="call_count" label="调用次数" width="100" align="center" />
      <el-table-column label="状态" width="80" align="center">
        <template #default="{ row }">
          <el-switch
            :model-value="row.enabled"
            @change="(val: boolean) => toggleEnabled(row, val)"
            size="small"
          />
        </template>
      </el-table-column>
      <el-table-column label="操作" width="200" align="center">
        <template #default="{ row }">
          <el-button type="primary" link size="small" @click="editApp(row)">编辑</el-button>
          <el-button type="warning" link size="small" @click="resetSecret(row)">重置密钥</el-button>
          <el-button type="info" link size="small" @click="showLogs(row)">日志</el-button>
          <el-button type="danger" link size="small" @click="deleteApp(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog v-model="dialogVisible" :title="editingApp ? '编辑应用' : '新建应用'" width="500px">
      <el-form :model="form" label-position="top">
        <el-form-item label="应用名称" required>
          <el-input v-model="form.name" placeholder="例如：外部调度系统" />
        </el-form-item>
        <el-form-item label="权限范围">
          <el-select
            v-model="form.scopesList"
            multiple
            filterable
            placeholder="留空表示全部权限"
            style="width: 100%"
          >
            <el-option v-for="s in scopeOptions" :key="s.value" :label="s.label" :value="s.value" />
          </el-select>
        </el-form-item>
        <el-form-item label="速率限制">
          <el-input-number v-model="form.rate_limit" :min="1" :max="10000" />
          <span style="margin-left: 8px; color: var(--el-text-color-secondary)">次/小时</span>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitForm">确定</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="secretDialogVisible" title="应用密钥" width="560px" :close-on-click-modal="false">
      <el-alert type="warning" :closable="false" style="margin-bottom: 16px">
        请妥善保管密钥，关闭后需要验证密码才能再次查看 App Secret。
      </el-alert>
      <div class="secret-display-card">
        <div class="secret-row">
          <span class="secret-label">App Key</span>
          <div class="secret-value-box">
            <code class="secret-value-text">{{ secretData.app_key }}</code>
            <el-button class="copy-btn" size="small" @click="copyText(secretData.app_key)">
              <el-icon><DocumentCopy /></el-icon> 复制
            </el-button>
          </div>
        </div>
        <div class="secret-row">
          <span class="secret-label">App Secret</span>
          <div class="secret-value-box">
            <code class="secret-value-text">{{ secretData.app_secret }}</code>
            <el-button class="copy-btn" size="small" @click="copyText(secretData.app_secret)">
              <el-icon><DocumentCopy /></el-icon> 复制
            </el-button>
          </div>
        </div>
      </div>
    </el-dialog>

    <el-dialog v-model="logsDialogVisible" title="调用日志" width="700px">
      <el-table :data="callLogs" size="small" max-height="400">
        <el-table-column prop="endpoint" label="接口" min-width="200" show-overflow-tooltip />
        <el-table-column prop="method" label="方法" width="80" />
        <el-table-column prop="status" label="状态码" width="80" align="center" />
        <el-table-column prop="duration" label="耗时(ms)" width="90" align="center" />
        <el-table-column prop="ip" label="IP" width="140" />
        <el-table-column prop="created_at" label="时间" width="170">
          <template #default="{ row }">
            {{ new Date(row.created_at).toLocaleString('zh-CN') }}
          </template>
        </el-table-column>
      </el-table>
      <el-pagination
        v-if="logTotal > 20"
        style="margin-top: 12px; justify-content: flex-end"
        layout="total, prev, pager, next"
        :total="logTotal"
        :page-size="20"
        v-model:current-page="logPage"
        @current-change="loadLogs"
      />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { openApiApi } from '@/api/open-api'
import { ElMessage, ElMessageBox } from 'element-plus'

const apps = ref<any[]>([])
const loading = ref(false)
const dialogVisible = ref(false)
const secretDialogVisible = ref(false)
const logsDialogVisible = ref(false)
const editingApp = ref<any>(null)
const secretData = ref<any>({})
const callLogs = ref<any[]>([])
const logTotal = ref(0)
const logPage = ref(1)
const currentLogAppId = ref(0)
const revealedSecrets = reactive<Record<number, string>>({})

const form = ref({ name: '', scopesList: [] as string[], rate_limit: 100 })

const scopeOptions = [
  { label: '任务管理', value: 'tasks' },
  { label: '脚本管理', value: 'scripts' },
  { label: '环境变量', value: 'envs' },
  { label: '日志查看', value: 'logs' },
  { label: '系统信息', value: 'system' },
]

const scopeLabelMap: Record<string, string> = Object.fromEntries(scopeOptions.map(s => [s.value, s.label]))

const parseScopesTags = (scopes: string): string[] => {
  if (!scopes) return []
  return scopes.split(',').map(s => s.trim()).filter(Boolean).map(s => scopeLabelMap[s] || s)
}

const scopesToString = (list: string[]): string => list.join(',')

const stringToScopes = (str: string): string[] => {
  if (!str) return []
  return str.split(',').map(s => s.trim()).filter(Boolean)
}

const copyText = async (text: string) => {
  if (!text) return
  try {
    await navigator.clipboard.writeText(text)
    ElMessage.success('已复制')
  } catch {
    const textarea = document.createElement('textarea')
    textarea.value = text
    textarea.style.position = 'fixed'
    textarea.style.opacity = '0'
    document.body.appendChild(textarea)
    textarea.select()
    document.execCommand('copy')
    document.body.removeChild(textarea)
    ElMessage.success('已复制')
  }
}

const loadApps = async () => {
  loading.value = true
  try {
    const res = await openApiApi.list()
    apps.value = (res as any).data || []
  } catch {} finally {
    loading.value = false
  }
}

const showCreateDialog = () => {
  editingApp.value = null
  form.value = { name: '', scopesList: [], rate_limit: 100 }
  dialogVisible.value = true
}

const editApp = (app: any) => {
  editingApp.value = app
  form.value = { name: app.name, scopesList: stringToScopes(app.scopes || ''), rate_limit: app.rate_limit || 100 }
  dialogVisible.value = true
}

const submitForm = async () => {
  if (!form.value.name) {
    ElMessage.warning('请输入应用名称')
    return
  }
  const payload = {
    name: form.value.name,
    scopes: scopesToString(form.value.scopesList),
    rate_limit: form.value.rate_limit,
  }
  try {
    if (editingApp.value) {
      await openApiApi.update(editingApp.value.id, payload)
      ElMessage.success('更新成功')
    } else {
      const res = await openApiApi.create(payload)
      secretData.value = (res as any).data || {}
      secretDialogVisible.value = true
      ElMessage.success('创建成功')
    }
    dialogVisible.value = false
    loadApps()
  } catch {
    ElMessage.error('操作失败')
  }
}

const viewSecret = async (app: any) => {
  try {
    const { value: password } = await ElMessageBox.prompt('请输入登录密码以查看 App Secret', '身份验证', {
      inputType: 'password',
      inputPlaceholder: '请输入密码',
      confirmButtonText: '确认',
      cancelButtonText: '取消',
    })
    if (!password) return
    const res = await openApiApi.viewSecret(app.id, password) as any
    revealedSecrets[app.id] = res.data?.app_secret || ''
  } catch (e: any) {
    if (e === 'cancel' || e?.toString() === 'cancel') return
    ElMessage.error(e?.response?.data?.error || '验证失败')
  }
}

const toggleEnabled = async (app: any, val: boolean) => {
  try {
    if (val) {
      await openApiApi.enable(app.id)
    } else {
      await openApiApi.disable(app.id)
    }
    app.enabled = val
  } catch {
    ElMessage.error('操作失败')
  }
}

const resetSecret = async (app: any) => {
  try {
    await ElMessageBox.confirm('确认重置密钥？旧密钥将立即失效。', '警告', { type: 'warning' })
    const res = await openApiApi.resetSecret(app.id)
    secretData.value = (res as any).data || {}
    secretDialogVisible.value = true
    delete revealedSecrets[app.id]
  } catch {}
}

const deleteApp = async (app: any) => {
  try {
    await ElMessageBox.confirm(`确认删除应用 "${app.name}"？`, '提示', { type: 'warning' })
    await openApiApi.delete(app.id)
    ElMessage.success('删除成功')
    loadApps()
  } catch {}
}

const showLogs = (app: any) => {
  currentLogAppId.value = app.id
  logPage.value = 1
  logsDialogVisible.value = true
  loadLogs()
}

const loadLogs = async () => {
  try {
    const res = await openApiApi.callLogs(currentLogAppId.value, {
      page: logPage.value,
      page_size: 20,
    })
    callLogs.value = (res as any).data || []
    logTotal.value = (res as any).total || 0
  } catch {}
}

onMounted(loadApps)
</script>

<style scoped lang="scss">
.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;

  h2 { margin: 0; font-size: 20px; font-weight: 700; color: var(--el-text-color-primary); }

  .page-subtitle {
    font-size: 13px;
    color: var(--el-text-color-secondary);
    display: block;
    margin-top: 2px;
  }
}

.key-display {
  display: flex;
  align-items: center;
  gap: 6px;
}

.key-code {
  font-size: 12px;
  word-break: break-all;
  background: var(--el-fill-color-light);
  padding: 4px 8px;
  border-radius: 4px;
  border: 1px solid var(--el-border-color-lighter);
  font-family: var(--dd-font-mono);
  flex: 1;
  min-width: 0;
}

.secret-code {
  background: var(--el-color-warning-light-9);
  border-color: var(--el-color-warning-light-5);
}

.secret-mask {
  color: var(--el-text-color-placeholder);
  letter-spacing: 2px;
}

.copy-btn {
  flex-shrink: 0;
  border: 1px solid var(--el-border-color);
  background: var(--el-fill-color-blank);
  &:hover {
    color: var(--el-color-primary);
    border-color: var(--el-color-primary-light-5);
    background: var(--el-color-primary-light-9);
  }
}

.secret-display-card {
  background: var(--el-fill-color-light);
  border-radius: 8px;
  padding: 20px;
  border: 1px solid var(--el-border-color-lighter);
}

.secret-row {
  &:not(:last-child) {
    margin-bottom: 16px;
    padding-bottom: 16px;
    border-bottom: 1px dashed var(--el-border-color-lighter);
  }
}

.secret-label {
  display: block;
  font-size: 13px;
  font-weight: 600;
  color: var(--el-text-color-secondary);
  margin-bottom: 8px;
}

.secret-value-box {
  display: flex;
  align-items: center;
  gap: 8px;
  background: var(--el-fill-color-blank);
  border: 1px solid var(--el-border-color);
  border-radius: 6px;
  padding: 10px 12px;
}

.secret-value-text {
  flex: 1;
  font-size: 13px;
  font-family: var(--dd-font-mono);
  word-break: break-all;
  line-height: 1.5;
}
</style>
